DROP TABLE IF EXISTS Roles
CREATE TABLE Roles
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL UNIQUE
)
INSERT INTO Roles(Name) VALUES ('Admin');
INSERT INTO Roles(Name) VALUES ('User');

DROP TABLE IF EXISTS UserRole
CREATE TABLE UserRole
(
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Username NVARCHAR(50) NOT NULL UNIQUE,
	Password NVARCHAR(25) NOT NULL,
	RoleID INT NOT NULL
)
INSERT INTO UserRole(Username, Password, RoleID) VALUES ('admin','admin',1);
ALTER TABLE UserRole
ADD CONSTRAINT FK_UserRole FOREIGN KEY (RoleID)
REFERENCES Roles(Id) ON DELETE CASCADE

DROP TABLE IF EXISTS Passenger
CREATE TABLE Passenger 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    UserID INT NOT NULL UNIQUE,
	Firstname NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL,
	Email VARCHAR(32) NOT NULL,
	PhoneNumber bigint NOT NULL, 
)
ALTER TABLE Passenger
ADD CONSTRAINT FK_PassengerRole FOREIGN KEY (UserID)
REFERENCES UserRole(Id) ON DELETE CASCADE

DROP TABLE IF EXISTS Place
CREATE TABLE Place 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
)

DROP TABLE IF EXISTS Route
CREATE TABLE Route 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Origin NVARCHAR(50) NOT NULL,
	Destination NVARCHAR(50) NOT NULL
)
--    OriginID INT NOT NULL,
--    DestinationID INT NOT NULL,
--)
--ALTER TABLE Route
--ADD CONSTRAINT FK_OriginID FOREIGN KEY (OriginID)
--REFERENCES Place(Id) ON DELETE CASCADE
--ALTER TABLE Route
--ADD CONSTRAINT FK_DestinationID FOREIGN KEY (DestinationID)
--REFERENCES Place(Id)

DROP TABLE IF EXISTS BusVehicle
CREATE TABLE BusVehicle 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name NVARCHAR(25) NOT NULL,
	RouteID INT NOT NULL,
	AC BIT NOT NULL, 
	Fare INT NOT NULL, 
	DepartureTime VARCHAR(5) NOT NULL
)
ALTER TABLE BusVehicle
ADD CONSTRAINT FK_BusRoute FOREIGN KEY (RouteID)
REFERENCES Route(Id) ON DELETE CASCADE

DROP TABLE IF EXISTS Ticket
CREATE TABLE Ticket 
(	
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Seat VARCHAR(3) NOT NULL,
	TimeStamp TIMESTAMP NOT NULL, 
	PassengerID int NOT NULL, 
	BusID int NOT NULL, 
	Date DATE NOT NULL
)
ALTER TABLE Ticket
ADD CONSTRAINT FK_TicketPassenger FOREIGN KEY (PassengerID)
REFERENCES Passenger(Id) ON DELETE CASCADE
ALTER TABLE Ticket
ADD CONSTRAINT FK_TicketBus FOREIGN KEY (BusID)
REFERENCES BusVehicle(Id) ON DELETE CASCADE